### ISSUE TITLE
Move from docker to kubernetes cluster to avoid downtime after deploy

### ISSUE THREAD

**Issue by kennhardy** [webbnik/TML-NFT-BOT#6]
Using a deploy manifest with a readinessProbe like this will allow the app to warm up prior to the active pod being switched out.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tml-nft-bot-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tml-nft-bot
  template:
    metadata:
      labels:
        app: tml-nft-bot
    spec:
      containers:
        - name: tml-nft-bot-container
          image: tml-nft-bot-image:latest
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "sleep 120"
            initialDelaySeconds: 120 
```
